project_name: webdav
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
 - env:
     - CGO_ENABLED=0
   goos:
     - linux
     - windows
     - darwin
     - freebsd
   goarch:
     - amd64
     - 386
     - arm
     - arm64
   goarm:
     - 5
     - 6
     - 7
   ignore:
     - goos: darwin
       goarch: 386
     - goos: freebsd
       goarch: arm
archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
